# 1) Introduction to NumPy

- for numerical calculations
- **numpy arrays** - specialized data structures 50x faster than python lists

# 2) Array creation 

- **np.array()**
- **np.zeros()** - pole vyplnene len nulami 0
- **np.ones()** - pole vyplnene len jednotkami 1
- **np.arange()** - vrati pole s hodnotami v definovanom intervale
- **np.random.rand()** - pole s nahodnymi hodnotami
- **np.empty()** - prazdne pole

## 2.1) Create array using Python list

In [ ]:
import numpy as np

# vytvorim list
my_list = [2, 4, 6, 8]

# vytvorim numpy array z listu
# my_list je argument pre numpy array
my_array = np.array(my_list)

# zobrazenie numpy array
print(my_array)

[2 4 6 8]


## 2.2) Create array using np.zeros(), np.ones()

In [5]:
import numpy as np

# vytvorim pole so 4 prvkami vyplnene len 0
my_array_zeros = np.zeros(4)

# vytvorim pole so 4 prvkami vyplnene len 0
my_array_ones = np.ones(4)

# zobrazenie
print("Array zeros", my_array_zeros)
print("Array ones", my_array_ones)

Array zeros [0. 0. 0. 0.]
Array ones [1. 1. 1. 1.]


## 2.3) Create array with np.arange()

In [ ]:
import numpy as np

# pole s hodnotami od 0 do 4
arr1 = np.arange(5)

# pole s hodnotami od 1 do 8 a krokom 2
arr2 = np.arange(1, 9, 2)

# zobrazenie
print(arr1)
print(arr2)

[0 1 2 3 4]
[1 3 5 7]


## 2.4) Create array with np.random.rand()

In [7]:
import numpy as np

# pole s 5 nahodnymi hodnotami
arr = np.random.rand(5)

# zobrazenie
print(arr)

[0.51746996 0.08061796 0.57182777 0.72292152 0.19594484]


## 2.5) Create empty array np.empty()

- aj napriek tomu, ze vytvarm prazdne pole, numpy, sa ho snazi vyplnit hodnotami, tie vsak nemaju ziaden vyznam. 

In [9]:
import numpy as np

# prazdne pole o dlzke 4 prvkov
arr = np.empty(4)

# zobrazenie
print(arr)

[1. 1. 1. 1.]
